name:                m3u8
version:             0.1.0.0
github:              "cloudcrypt/m3u8"
license:             BSD3
author:              "Daniel D"
maintainer:          "cloudcrypt@users.noreply.github.com"
copyright:           "2019 Daniel D"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
synopsis:            Haskell library for m3u8 stream parsing, downloading, and decrypting.
category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/m3u8#readme>

dependencies:
- base >= 4.7 && < 5
- text
- directory
- bytestring
- binary
- regex-posix
- http-conduit
- ascii-progress
- async
- SafeSemaphore
- SimpleAES
- hxt-unicode
- containers
- split

library:
  source-dirs: src


# executables:
#   m3u8-exe:
#     main:                Main.hs
#     source-dirs:         app
#     ghc-options:
#     - -threaded
#     - -rtsopts
#     - -with-rtsopts=-N
#     dependencies:
#     - m3u8

tests:
  m3u8-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - m3u8
